server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: toor
    url: jdbc:postgresql://localhost:5432/carshare
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true